language: python
python:
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install psycopg2-binary

services:
- postgresql

before_script:
- export FLASK_ENV=testing
- psql -c 'create database test_questioner;' -U postgres
- export DATABASE_URL = "dbname='test_questioner' host='localhost' port='5432' user='postgres' password=''"
script: 
  - coverage run --source=app -m pytest && coverage report 

after_success:
  - coveralls

cache: pip3