language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

services:
  - postgresql

before_script:
- psql -c "create database test_questioner;" -U postgres
- psql -c "create user postgres WITH PASSWORD 'bonbon';" -U postgres

script: 
  - export APP_SETTINGS="testing"
  - export SECRET="iamsecret"
  - export DB_TESTING_URL="dbname='test_questioner' user='postgres' password='bonbon'"
  
  - pytest --cov-report term-missing --cov=app
  - coveralls

after_success:
  - coveralls
  
cache:
  - pip